# CREADO POR GITHUB: CHANGO01

# miniPiano usando PyQt5. El diseño está realizado en el 'designer' de PyQt5, luego se convierte el archivo .ui a .py 
# mediante la ejecución en el cmd "/pyuic5 -x "rutadelarchivo/nombre.ui" -o "rutadelnuevoarchivo/nombre.py"
# para realizar el desarrollo de la función que va a ejecutar cada tecla del piano. La mayor parte del código se crea al hacer 
# la conversión de .ui a .py, se agregan algunos detalles del color y la función de los botones(teclas).

from PyQt5 import QtCore, QtGui, QtWidgets      
from playsound import playsound                     # Para reproducir los archivos de audio.

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("background-color: #d4b6b6")
        MainWindow.resize(650, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 631, 211))
        self.frame.setStyleSheet("background-color: #bd250d")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.do0 = QtWidgets.QPushButton(self.frame)            # Crea el objeto con las medidas, el color de fondo lo agregue en el archivo.py,
        self.do0.setGeometry(QtCore.QRect(50, 70, 41, 141))     # sin texto y con el nombre del objeto que es el que luego se pasa como parámetro.
        self.do0.setStyleSheet("background-color: #cc2910")
        self.do0.setText("")
        self.do0.setObjectName("do0")
        self.do0.clicked.connect(lambda: self.play("do0"))      # Se llama a la función self.play usando lambda para pasar parámetro.
        self.re0 = QtWidgets.QPushButton(self.frame)            # Se repiten los pasos para cada tecla.
        self.re0.setGeometry(QtCore.QRect(90, 70, 41, 141))
        self.re0.setStyleSheet("background-color: #cc2910")
        self.re0.setText("")
        self.re0.setObjectName("re0")
        self.re0.clicked.connect(lambda: self.play("re0"))
        self.mi0 = QtWidgets.QPushButton(self.frame)        
        self.mi0.setGeometry(QtCore.QRect(130, 70, 41, 141))
        self.mi0.setStyleSheet("background-color: #cc2910")
        self.mi0.setText("")
        self.mi0.setObjectName("mi0")
        self.mi0.clicked.connect(lambda: self.play("mi0"))
        self.fa0 = QtWidgets.QPushButton(self.frame)
        self.fa0.setGeometry(QtCore.QRect(170, 70, 41, 141))
        self.fa0.setStyleSheet("background-color: #cc2910")
        self.fa0.setText("")
        self.fa0.setObjectName("fa0")
        self.fa0.clicked.connect(lambda: self.play("fa0"))
        self.sol0 = QtWidgets.QPushButton(self.frame)
        self.sol0.setGeometry(QtCore.QRect(210, 70, 41, 141))
        self.sol0.setStyleSheet("background-color: #cc2910")
        self.sol0.setText("")
        self.sol0.setObjectName("sol0")
        self.sol0.clicked.connect(lambda: self.play("sol0"))
        self.la0 = QtWidgets.QPushButton(self.frame)        
        self.la0.setGeometry(QtCore.QRect(250, 70, 41, 141))
        self.la0.setStyleSheet("background-color: #cc2910")
        self.la0.setText("")
        self.la0.setObjectName("la0")
        self.la0.clicked.connect(lambda: self.play("la0"))
        self.si0 = QtWidgets.QPushButton(self.frame)        
        self.si0.setGeometry(QtCore.QRect(290, 70, 41, 141))
        self.si0.setStyleSheet("background-color: #cc2910")
        self.si0.setText("")
        self.si0.setObjectName("si0")
        self.si0.clicked.connect(lambda: self.play("si0"))
        self.do1 = QtWidgets.QPushButton(self.frame)        
        self.do1.setGeometry(QtCore.QRect(330, 70, 41, 141))
        self.do1.setStyleSheet("background-color: #cc2910")
        self.do1.setText("")
        self.do1.setObjectName("do1")
        self.do1.clicked.connect(lambda: self.play("do1"))
        self.re1 = QtWidgets.QPushButton(self.frame)        
        self.re1.setGeometry(QtCore.QRect(370, 70, 41, 141))
        self.re1.setStyleSheet("background-color: #cc2910")
        self.re1.setText("")
        self.re1.setObjectName("re1")
        self.re1.clicked.connect(lambda: self.play("re1"))
        self.mi1 = QtWidgets.QPushButton(self.frame)        
        self.mi1.setGeometry(QtCore.QRect(410, 70, 41, 141))
        self.mi1.setStyleSheet("background-color: #cc2910")
        self.mi1.setText("")
        self.mi1.setObjectName("mi1")
        self.mi1.clicked.connect(lambda: self.play("mi1"))
        self.doS0 = QtWidgets.QPushButton(self.frame)        
        self.doS0.setGeometry(QtCore.QRect(80, 70, 21, 81))
        self.doS0.setStyleSheet("background-color: #b88d86")
        self.doS0.setText("")
        self.doS0.setObjectName("doS0")
        self.doS0.clicked.connect(lambda: self.play("doS0"))
        self.reS0 = QtWidgets.QPushButton(self.frame)        
        self.reS0.setGeometry(QtCore.QRect(120, 70, 21, 81))
        self.reS0.setStyleSheet("background-color: #b88d86")
        self.reS0.setText("")
        self.reS0.setObjectName("reS0")
        self.reS0.clicked.connect(lambda: self.play("reS0"))
        self.faS0 = QtWidgets.QPushButton(self.frame)        
        self.faS0.setGeometry(QtCore.QRect(200, 70, 21, 81))
        self.faS0.setStyleSheet("background-color: #b88d86")
        self.faS0.setText("")
        self.faS0.setObjectName("faS0")
        self.faS0.clicked.connect(lambda: self.play("faS0"))
        self.solS0 = QtWidgets.QPushButton(self.frame)        
        self.solS0.setGeometry(QtCore.QRect(240, 70, 21, 81))
        self.solS0.setStyleSheet("background-color: #b88d86")
        self.solS0.setText("")
        self.solS0.setObjectName("solS0")
        self.solS0.clicked.connect(lambda: self.play("solS0"))
        self.laS0 = QtWidgets.QPushButton(self.frame)        
        self.laS0.setGeometry(QtCore.QRect(280, 70, 21, 81))
        self.laS0.setStyleSheet("background-color: #b88d86")
        self.laS0.setText("")
        self.laS0.setObjectName("laS0")
        self.laS0.clicked.connect(lambda: self.play("laS0"))
        self.doS1 = QtWidgets.QPushButton(self.frame)        
        self.doS1.setGeometry(QtCore.QRect(360, 70, 21, 81))
        self.doS1.setStyleSheet("background-color: #b88d86")
        self.doS1.setText("")
        self.doS1.setObjectName("doS1")
        self.doS1.clicked.connect(lambda: self.play("doS1"))
        self.reS1 = QtWidgets.QPushButton(self.frame)        
        self.reS1.setGeometry(QtCore.QRect(400, 70, 21, 81))
        self.reS1.setStyleSheet("background-color: #b88d86")
        self.reS1.setText("")
        self.reS1.setObjectName("reS1")
        self.reS1.clicked.connect(lambda: self.play("reS1"))
        self.fa1 = QtWidgets.QPushButton(self.frame)        
        self.fa1.setGeometry(QtCore.QRect(450, 70, 41, 141))
        self.fa1.setStyleSheet("background-color: #cc2910")
        self.fa1.setText("")
        self.fa1.setObjectName("fa1")
        self.fa1.clicked.connect(lambda: self.play("fa1"))
        self.sol1 = QtWidgets.QPushButton(self.frame)        
        self.sol1.setGeometry(QtCore.QRect(490, 70, 41, 141))
        self.sol1.setStyleSheet("background-color: #cc2910")
        self.sol1.setText("")
        self.sol1.setObjectName("sol1")
        self.sol1.clicked.connect(lambda: self.play("sol1"))
        self.la1 = QtWidgets.QPushButton(self.frame)        
        self.la1.setGeometry(QtCore.QRect(530, 70, 41, 141))
        self.la1.setStyleSheet("background-color: #cc2910")
        self.la1.setText("")
        self.la1.setObjectName("la1")
        self.la1.clicked.connect(lambda: self.play("la1"))
        self.si1 = QtWidgets.QPushButton(self.frame)        
        self.si1.setGeometry(QtCore.QRect(570, 70, 41, 141))
        self.si1.setStyleSheet("background-color: #cc2910")
        self.si1.setText("")
        self.si1.setObjectName("si1")
        self.si1.clicked.connect(lambda: self.play("si1"))
        self.faS1 = QtWidgets.QPushButton(self.frame)        
        self.faS1.setGeometry(QtCore.QRect(480, 70, 21, 81))
        self.faS1.setStyleSheet("background-color: #b88d86")
        self.faS1.setText("")
        self.faS1.setObjectName("faS1")
        self.faS1.clicked.connect(lambda: self.play("faS1"))
        self.solS1 = QtWidgets.QPushButton(self.frame)        
        self.solS1.setGeometry(QtCore.QRect(520, 70, 21, 81))
        self.solS1.setStyleSheet("background-color: #b88d86")
        self.solS1.setText("")
        self.solS1.setObjectName("solS1")
        self.solS1.clicked.connect(lambda: self.play("solS1"))
        self.laS1 = QtWidgets.QPushButton(self.frame)        
        self.laS1.setGeometry(QtCore.QRect(560, 70, 21, 81))
        self.laS1.setStyleSheet("background-color: #b88d86")
        self.laS1.setText("")
        self.laS1.setObjectName("laS1")
        self.laS1.clicked.connect(lambda: self.play("laS1"))
        self.label = QtWidgets.QLabel(self.frame)        
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("chango01 - miniPiano", "chango01 - miniPiano"))
        self.label.setText(_translate("MainWindow", "CHANGO01"))

    def play(self,val):                         # Única función que recibe el nombre de la nota como parámetro
        playsound('{}.mp3'.format(val))         # para llamar y reproducir los archivos de audio.


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
